tulip/oplogtoredis

- README.md
Adjusted the name of the parameter for the configuration of the prefix for redis as it changed in version 1.2.7 of `redis-oplog`.
> Fixed compatibility of readme to redis-oplog v1.2.7

- README.md
- blackbox-tests/docker-compose.yml
- lib/config/main.go
- lib/config/main_test.go
- lib/mongourl/parse_test.go
- main.go
Testing: Managed to connect to a redis instance on aws over TLS.
> use rediss:// to specify to use TLS instead of env variable config

- lib/oplog/processor.go
- lib/oplog/processor_test.go
- lib/redispub/publication.go
- lib/redispub/publisher.go
- lib/redispub/publisher_test.go
The design as currently is only allows sending a message into two channels:
* Collection channel
* Individual channel
This PR is a first improvement of this design towards supporting custom channels, as used when fine-tuning the `redis-oplog` package: https://github.com/cult-of-coders/redis-oplog/blob/master/docs/finetuning.md
It doesn't change anything on the actual result, but allows the processor to define a list of channels instead of expecting two channels.
The publisher receives the `Publication` documents and concatenates the channels, which Redis (using a LUA script) then splits again to get the list of channels in which it can send the message to.
Decision taken:
Since the arguments, passed to LUA only accepts strings, we have to concatenate the list of channels to a string - …
> Open up for sending the message to more than two channels

- .github/actions/setup-ecr-buildx/action.yml
- .github/workflows/build-and-push.yml
- .github/workflows/pull-request.yml
- Dockerfile.integration
- README.md
- default.nix
- flake.lock
- go.mod
- go.sum
- integration-tests/acceptance/harness_test.go
- integration-tests/fault-injection/baseline_test.go
- integration-tests/fault-injection/harness/inserter.go
- integration-tests/fault-injection/harness/mongo.go
- integration-tests/fault-injection/harness/redis.go
- integration-tests/fault-injection/harness/redisVerifier.go
- integration-tests/fault-injection/mongoStepdown_test.go
- integration-tests/fault-injection/mongoStopStart_test.go
- integration-tests/fault-injection/restart_test.go
- integration-tests/helpers/redis.go
- integration-tests/performance/bench_test.go
- lib/oplog/oplogEntry_test.go
- lib/oplog/tail.go
- lib/oplog/tail_test.go
- lib/redispub/lastProcessedTime.go
- lib/redispub/lastProcessedTime_test.go
- lib/redispub/publisher.go
- lib/redispub/publisher_test.go
- main.go
- scripts/install-debian-mongo.sh
- scripts/runIntegrationFaultInjection.sh
We're moving our Docker image hosting from Docker Hub to AWS Public ECR Repositories. 
Additionally this PR also attempts to fix failures in the tests that were undetected in the last merge as we just added these workflows.
> GHA: Build and Publish to Public ECR and Build Nix

- default.nix
- docker-compose.yml
- integration-tests/acceptance/docker-compose.yml
- integration-tests/acceptance/harness_test.go
- integration-tests/helpers/redis.go
- integration-tests/performance/docker-compose.yml
- lib/config/main.go
- lib/config/main_test.go
- lib/oplog/tail.go
- lib/oplog/tail_test.go
- lib/redispub/publisher.go
- main.go
- Made oplogtoredis mirror between multiple redis instances, given multiple, comma separated REDIS_URL's
- upgraded the tests to verify this behavior
- added sentinel support
- existing integration tests and manual testing
> GoSentinel: Added redis-sentinel support

- docker-compose.yml
- integration-tests/acceptance/docker-compose.yml
- integration-tests/performance/docker-compose.yml
- lib/parse/main.go
- main.go
Schema is defined here: https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details#uri-syntax
OTR_REDIS_URL value should be comma-separated as before, and each term should either be a regular `redis://` URL, or one of these lettuce pseudo-url entries.
Updated the docker-compose test files to use this schema for sentinel.
The tests themselves  still connect directly to the sentinel cluster, but OTR running in the tests will parse the URLs as described.
> Use Lettuce schema for Redis Sentinel URLs

- default.nix
- main.go
Update oplogtoredis to serve the standard net/http/pprof routes from its existing HTTP server. You can try it out by running `go tool pprof http://<host and port for oplogtoredis>`.
> Add pprof endpoints

- scripts/runBlackboxTests.sh
- scripts/runIntegrationAcceptance.sh
- scripts/runIntegrationAcceptanceSingle.sh
- scripts/runIntegrationMeteor.sh
- scripts/runIntegrationPerformance.sh
CI broke as of 2024/04/01 because of [this](https://github.com/actions/runner-images/issues/9557). I update all of the references to `docker-compose` to `docker compose` as recommended, which seems to have fixed it. All jobs passed, and at least some of them ran on the new image (I'm not entirely sure what controls this; perhaps which runner the job hits?), which tells me that this change works in both circumstances.
> Update various usages of `docker-compose` to `docker compose`

- default.nix
- lib/oplog/tail.go
- lib/redispub/publisher.go
- main.go
Adds a few new metrics:
- `otr_pubsub_last_command_duration_seconds`
- `otr_oplog_last_entry_staleness_seconds`
- `otr_buffer_available`
This has been baking in staging since before the weekend and seems to be working nicely.
> Add some new metrics

- default.nix
- lib/oplog/tail.go
When we get an oplog entry, we log it out at debug level. This adds an extra metadata field that prints the server time in seconds since the epoch so that it's easy to see visually how delayed oplog entries are.
> Add epoch-seconds timestamp to debug logs of oplog entries

- lib/config/main.go
- lib/oplog/processor.go
- lib/oplog/processor_test.go
- lib/oplog/tail.go
- lib/redispub/publication.go
- main.go
This adds a new configuration option, OTR_WRITE_PARALLELISM. This will be an integer that controls how many parallel writer loops deliver the oplog messages to Redis. Each oplog message will be routed to one of the loops based on a SHA256 hash of its database name. The value defaults to 1 if unspecified, which means it parallelism is off by default (since a parallelism of 1 means a single writer, the same as currently).
> Oplogtoredis: Add configurable Write Parallelism

- integration-tests/fault-injection/redisStopStart_test.go
- lib/config/main.go
- lib/oplog/tail.go
- lib/redispub/publisher.go
- main.go
This is a follow-on to https://github.com/tulip/oplogtoredis/pull/70.
This adds read parallelism in addition to the write-parallelism. Every read routine has its own Mongo session, and will consume the entire oplog. When processing a message, the same hash that is used to route the message to the appropriate write routine will be first compared to the ordinal of the read routine. If it doesn't match, it will simply be discarded. The result of this is that every message will be processed by exactly one read routine.
The read routines need not correspond one-to-one with the write routines.
> OplogToRedis: Read Parallelism

- lib/denylist/http.go
If you try to DELETE at /denylist/:id and `id` doesn't exist on the denylist, the server will return 204 instead of 404, so that it can be done multiple times without producing an error.
> OplogToRedis: Make Denylist Deletion Idempotent

- default.nix
- lib/oplog/tail.go
- main.go
Revert https://github.com/tulip/oplogtoredis/pull/75
Also bump to 3.5 for all the parallelism & orchestration changes
> OplogToRedis: Revert broken parallelism change

- default.nix
- go.mod
- go.sum
- integration-tests/acceptance/denylist_http_test.go
- integration-tests/acceptance/denylist_oplog_test.go
- integration-tests/fault-injection/Dockerfile
- integration-tests/fault-injection/denylist_persistence_test.go
- integration-tests/fault-injection/harness/postgres.go
- integration-tests/helpers/http.go
- lib/config/main.go
- lib/denylist/http.go
- lib/denylist/pg.go
- main.go
Persist the configurable denylist across a restart.
The service takes an optional environment variable configuration option `OTR_PG_PERSISTENCE_URL` to a postgres database.
The service will create a table `otr_denylist` with one column (a list of unique denylist entries).
The service will write to the table whenever entries are created or removed.
Since all OTR replicas should have the same denylist, this should be fine- first to add adds, and first to delete deletes.
The service will read the table contents at startup to populate the initial denylist.
This should make the service resilient to restarting after a denylist entry was added.
The HTTP methods should only respond 2xx after writing to the DB, so persistence failures will be known by the calling context.
> OplogToRedis: Persistent Denylist

- lib/oplog/tail.go
- main.go
Redo https://github.com/tulip/oplogtoredis/pull/75
in main, count through each redis client and make a separate chan and coroutine for clientsCount * ordinalCount different entries. make some changes to aggregation in order to accomodate this.
in the tailer, get the [][]chan and for each incoming publication, first index by the shard ordinal (hash of db name), then iterate through the remaining chans (should be one for each redis client) and publish to all of them. 
at present, the publisher stream still accepts an array, but now it's only getting one (each).
[fixed](https://github.com/tulip/oplogtoredis/pull/78/commits/66e79df5f3da819e8da399bc6551d41de66f5781) array index out of bounds issue
> OplogToRedis: Write Parallelism per-Redis (PR Redo)

- default.nix
- lib/redispub/publisher.go
Replace the last_command_duration_seconds gauge with redis_command_duration_seconds, a histogram. Also partition it by shard ordinal. Add an additional metric, entry_staleness_seconds, which is like last_entry_staleness_seconds except that it's a histogram rather than a gauge.
> Convert staleness and redis RTT metrics to histograms

- default.nix
- lib/oplog/tail.go
The last PR merged decode the objectID as either string or objectId type, but would fail on binary objectIDs.  The prior implementation had converted the objectID to an interface{} type, to be handled downstream, so this moves back to that approach, while still limiting the unmarshaling to just the _id field.
> Correction for objectID issue in last merge

- default.nix
- lib/log/main.go
The sentry client wasn't initialized, causing a segfault when reporting error logs.  The fix was tested by creating a test error after init, and confirm that the error showed up in Sentry.
> Sentry fix

- lib/oplog/tail.go
- lib/oplog/tail_test.go
Before entries can be masked out, or filtered by shard, an initial set of oplog entry metadata needs to be processed.  This is currently done via the rawOplogEntry type which is populated using bson.Unmarshal(), but this is much slower compared to accessing the necessary properties directly using bson methods.  Additionally, the namespace entry can be accessed before anything else, so that filtering can happen as far upstream as possible.
Benchmarking shows that small entries are 2x as fast, while the largest entries can be 100x faster.
> Improve initial metadata read using bson instead of unmarshal

- default.nix
- lib/config/main.go
- lib/config/main_test.go
- lib/oplog/tail.go
Previously the max catchup time default was 1 minute, which wasn't always enough to recover from a pod restart.  This
1. doubles the time to 2 minutes 
2. and also increases the dedup key TTL from 2m to 2.5m to allow for covering the catchup time without greatly increasing the number of keys (25% increase in total dedup keys, same create/expire rate).
3. Also added is `resume_failed` metric that increments each time it cannot catchup from where it left off.
4. Logging is also improved with the addition of last processed age in seconds.
> Add metric for catchup failure and increase catchup time to 2 minutes

- default.nix
- main.go
Oplogtoredis already captured the SIGINT signal, but this adds SIGTERM as well, which is what k8s sends for termination of a pod.  This allows for graceful and clean shutdown.  Also corrects a panic from the HTTP server exit that was interrupting the clean shutdown process.  Tested locally and confirmed shutdown is working as expected.
> Clean shutdown

- default.nix
- lib/redispub/publisher.go
Oplogtoredis runs two replicas in parallel which both write to redis, with dedup being done by a lua script.  However, both of these replicas report the latency in time to reach redis, regardless of whether it was the first to reach redis or not.  This means that is one replica is lagging behind, it will report larger latency values than what’s actually reaching redis, and we don’t have a way to filter these since they will be reported at a later time than the earlier successful write from the other replica.
This adds a return value to the dedup script and uses it as a label for the latency metrics.
Note: for some reason returning true/false from the lua script was causing the performance and fault_injection tests to fail (after an extra long time).  Switching to int, returning 1 or 2, …
> Add label to staleness metrics to distinguish published vs duplicate entries

- default.nix
- lib/oplog/tail.go
For commands that aren't transactions, we can safely ignore the missing applyOps key, since that key will only be there when it is a transaction.  All other commands that do not include the applyOps key apply only to the admin db, so there is no need to further process these.
> Downgrade benign error log to info

- default.nix
- lib/denylist/http.go
When the denylist fails to update due to a database error, the error is now logged.
Please select exactly one option. To change the level of impact, first unselect the current level of impact and then select the new level of impact.
This is a logging only change, and it's not an error level log.
none
Please select exactly one option. To change the release change category, first unselect the current category and then select the new one.
none
n/a
Check each when they are done or confirmed to not apply. If something here isn't checked, this isn't ready to be merged. Seriously. You are making your colleagues lives a lot easier by doing this consistently. Be a good Tulipian.
For more information on the requirements for every pull request, see [Development Definition of …
> OplogToRedis: Better Logging for Denylist Failures

- .github/workflows/pull-request.yml
- default.nix
- lib/denylist/http.go
When an item in the denylist is deleted, the former behavior didn't provide any feedback as to whether it existed or not.  This PR adds a log warning and returns 404 for a delete attempt on an entry not in the denylist.
Additionally, the acceptance test runner was updated to ubuntu 24.04 because 20.04 was deprecated on 4/15.
> Log and return error for delete denylist that doesn't exist

- default.nix
- lib/oplog/oplogEntry.go
- lib/oplog/oplog_v2_converter.go
- lib/oplog/tail.go
Changes structured data in logs to exclude document values when logging above the debug level. When available, operation keys are logged. Otherwise, structured logs include only oplog entry metadata.
Logs at the debug level were not modified. Logged redis messages were also unchanged, since they include only changed field names and not values.
> Avoid logging document values above debug level

- Dockerfile.dev
- Dockerfile.integration
- blackbox-tests/Dockerfile.oplogtoredis-blackbox
- integration-tests/fault-injection/Dockerfile
- integration-tests/fault-injection/harness/postgres.go
- integration-tests/fault-injection/harness/waitTCP.go
- scripts/install-debian-mongo.sh
- testapp/Dockerfile
Upgrades the Docker image tags used for Debian-based images in development and test containers, since versions based on Debian "buster" no longer run due to offline repositories. As a stopgap, these are upgraded to the same tool versions but with images based on "bullseye", since there is a chain of incompatibilities related to an outdated MongoDB driver that makes further upgrades more difficult. Those will be addressed in future changes.
> Upgrade Debian Docker image tags for dev and test containers

- default.nix
- lib/denylist/http.go
When oplogtoredis receives an HTTP request to delete an entry from the denylist, if the entry doesn't exist, this [commit](https://github.com/tulip/oplogtoredis/commit/e1488dbf6af561a0a88c9ffe4a11271d23bb9fb3#diff-245563af9e34754739b12b294f3324c1d42c116ace7ce8735e21dfbc82d8e064) made it such that the response is a 404. However, this causes issues with deployment operations at Tulip, where it is valid to send a DELETE request for a denylist entry even if it was never added. This change returns to old behavior, where a 204 was returned in these cases.
> Denylist: Return 204 when non-existent entry is deleted from denylist
